var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3ac36288._.js")
R.c("server/chunks/ssr/_eca94d92._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_1ca59552._.js")
R.c("server/chunks/ssr/[root-of-the-server]__47b7a64b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__74deccaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_07951b80._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__02590aa9._.js")
R.c("server/chunks/ssr/src_696f2c09._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_blog_[slug]_page_actions_ec3909d7.js")
R.m(18452)
module.exports=R.m(18452).exports
