var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/kontakt/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4deefb16._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_a2a524d2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__74deccaa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_07951b80._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__02590aa9._.js")
R.c("server/chunks/ssr/src_696f2c09._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_kontakt_page_actions_1ae154bd.js")
R.m(43757)
module.exports=R.m(43757).exports
